# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'Nutrify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nutrify
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Alamofire', '~> 5.1'
  pod 'FirebaseFirestoreSwift'
  pod 'SwiftOverlays'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

end
